#!/bin/bash

# Install NWChem with OpenMP + MPI parallelism method on AWS EC2 system
# Intel Parallel Studio for Linux 2019 update edition 5
#  - Intel C++ and Fortran compilers 
#  - Intel MPI & MKL (BLAS, LAPACK, ScaLAPACK)
# ARMCI MPI-PR for high efficient calculation

##----------------------- Intel library -------------------------------
source /opt/intel/parallel_studio_xe_2019/bin/psxevars.sh intel64
source /opt/intel/impi/2019.5.281/intel64/bin/mpivars.sh intel64 
source /opt/intel/bin/compilervars.sh intel64
source /opt/intel/mkl/bin/mklvars.sh intel64
##----------------------- NWChem configuration ------------------------
export NWCHEM_TOP=/home/nutt/nwchem-6.8.1
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all python"
export MAKE=/usr/bin/make
export USE_NOFSCHECK=TRUE
export LARGE_FILES=TRUE
export PYTHONHOME=/usr
export PYTHONVERSION=2.7
export USE_PYTHONCONFIG=y
export USE_PYTHON64=y
export USE_64TO32=y
export MRCC_METHODS=TRUE
export CCSDTQ=y
export CCSDTLR=y
export IPCCSD=y
export EACCSD=y
##----------------------- Intel compiler ------------------------------
export CC=icc
export FC=ifort link
##----------------------- OpenMP support ------------------------------
export USE_OPENMP=T
##------------------------ ARMCI support ------------------------------
export ARMCI_NETWORK=MPI-PR
## ---------------------- Intel MPI support ---------------------------
export MPI_ROOT="/opt/intel/impi/2019.5.281/intel64"
export MPICC="$MPI_ROOT/bin/mpiicc"
export MPICXX="$MPI_ROOT/bin/mpiicpc"
export MPIFC="$MPI_ROOT/bin/mpiifort"
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPI_DIR="${MPI_ROOT}"
export MPI_LOC=${MPI_DIR}
export MPIEXEC="${MPI_DIR}/bin/mpirun"
#---generated by $NWCHEM_TOP/src/tools/guess-mpidefs
export MPI_INCLUDE="/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/include/gfortran/7.1.0 -I/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/include"
export MPI_LIB="/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/release -L/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib"
export LIBMPI="-lmpifort -lmpi -lrt -lpthread -ldl"
## ---------------------- Math support --------------------------------
export MKLROOT="$INTEL_ROOT/mkl"
export MKLLIB="${MKLROOT}/lib/intel64"
export MKLINC="${MKLROOT}/include"
export HAS_BLAS=yes
export BLAS_SIZE=8
export BLASOPT="-L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl"
export LAPACK_SIZE=8
export LAPACK_LIB="$BLASOPT"
export LAPACK_LIBS="$BLASOPT"
export USE_SCALAPACK=y
export SCALAPACK_SIZE=8
export SCALAPACK="-L${MKLROOT}/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_ilp64 -liomp5 -lpthread -lm -ldl"
export SCALAPACK_LIB=${SCALAPACK}
export SCALAPACK_LIBS=${SCALAPACK}
## --------------------------------------------------------------------

export USE_64TO32=y

cd $NWCHEM_TOP/src

## Uncomment following three command lines for recompilation
#find ./ -name "dependencies" -exec rm {} \; -print
#make clean
#rm -f 64_to_32 32_to_64 tools/build tools/install

make nwchem_config
make 64_to_32
make FC=ifort
